DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS heights;
DROP TABLE IF EXISTS real_temperatures;
DROP TABLE IF EXISTS temperatures;
DROP TABLE IF EXISTS modes;
DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS alarms;
DROP TABLE IF EXISTS sleep_stats;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  active INTEGER DEFAULT 0
);

CREATE TABLE heights (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value REAL NOT NULL
);

CREATE TABLE real_temperatures (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value REAL NOT NULL,
  status TEXT NOT NULL
);

CREATE TABLE temperatures (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value REAL NOT NULL
);

CREATE TABLE modes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value TEXT NOT NULL,
  active INTEGER DEFAULT 0,
  height REAL NOT NULL,
  temperature REAL NOT NULL
);

CREATE TABLE songs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  song_path TEXT NOT NULL,
  active INTEGER DEFAULT 0
);

CREATE TABLE alarms (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  start TIMESTAMP NOT NULL,
  duration INTEGER NOT NULL,
  song_id INTEGER NOT NULL,
  FOREIGN KEY (song_id) REFERENCES songs (id)
);

CREATE TABLE sleep_stats (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  start TIMESTAMP NOT NULL,
  end TIMESTAMP NOT NULL,
  rating INTEGER NOT NULL
);

